### PR TITLE
feat: align Sidero servers list outlook with the wireframes

### PR DESCRIPTION
**Pull request by Unix4ever**
Just rewamped the UI of that page to be in sync with the wireframes we
have.
Also implemented expand/collapse for each item in the row to show more
details.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

### CODE REVIEW

**Comment by Unix4ever** [comment]
image

**Review by andrewrynhard — DISMISSED** [review]
Looks awesome.

**Pull request merged**
