### PR TITLE
feat: implement appearance settings modal window

### PR DESCRIPTION
**Pull request by Unix4ever**
Introduced a generic primitives for viewing modal windows.

Also reused shell component in settings view.

This PR helped to learn more about Vue 3 composition API primitives like
`ref` and `watch`.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

### CODE REVIEW

**Review by smira — APPROVED** [review]
lgtm, but I'm not much of a frontend dev

**Review by andrewrynhard — APPROVED** [review]

**Pull request merged**
