### PR TITLE
chore: define constants for all used resource types

### PR DESCRIPTION
**Pull request by Unix4ever**
This is crucial if the code base grows in the future.
If we update resource versions or change names in Talos it will be
easier to update them everywhere.

Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>

### CODE REVIEW

**Review by smira — APPROVED** [review]
we have them in `machinery` as well, but idk if we could import that into TS?

probably with `go generate` generating TS?

**Comment by Unix4ever** [comment]
> probably with go generate generating TS?

yeah something like that can be really cool.
This will be the first step towards it and then we can automate it.

**Pull request merged**
